import * as COLORS from "../colors/colors"
import { Color_String_Map, Theme } from "./theme"

export const Dark_Theme_Color_Map: Color_String_Map =
{
    main_blue$: COLORS.Smart_ROS_All_Colors.Tech_Blue_300,
    unlock_button_color$: COLORS.Smart_ROS_All_Colors.Strong_Blue_900,
    alarm_red_background$: COLORS.Smart_ROS_All_Colors.Custom_Red,
    active_gray_background$: COLORS.Smart_ROS_All_Colors.Gray_600,
    disabled_blue$: COLORS.Smart_ROS_All_Colors.Strong_Blue_100,
    slider_background_active$: COLORS.Smart_ROS_All_Colors.Tech_Blue_300,
    slider_background_inactive$: COLORS.Smart_ROS_All_Colors.Strong_Blue_300,
    circular_button_inactive$: COLORS.Smart_ROS_All_Colors.Gray_900,
    circular_button_active$: COLORS.Smart_ROS_All_Colors.Tech_Blue_300,
    theme_background$: COLORS.Smart_ROS_All_Colors.Gray_900,
    keypad_widget_background$: COLORS.Smart_ROS_All_Colors.Gray_700,
    widget_background$: COLORS.Smart_ROS_All_Colors.Gray_800,
    header_card_background$: COLORS.Smart_ROS_All_Colors.Gray_500,
    secondary_button_background$: COLORS.Smart_ROS_All_Colors.Gray_800,
    secondary_button_border$: COLORS.Smart_ROS_All_Colors.Tech_Blue_200,
    boxed_numeric_background$: COLORS.Smart_ROS_All_Colors.Gray_700,
    boxed_numeric_border$: COLORS.Smart_ROS_All_Colors.Gray_500,
    main_font_inactive$: COLORS.Smart_ROS_All_Colors.Gray_100,
    line_font$: COLORS.Smart_ROS_All_Colors.Gray_200,
    main_font_active$: COLORS.Smart_ROS_All_Colors.White,
    automation_step_font$: COLORS.Smart_ROS_All_Colors.Gray_100,
    automation_step_default$: COLORS.Smart_ROS_All_Colors.Gray_600,
    stopped_automation_font$: COLORS.Smart_ROS_All_Colors.Gray_100,
    notificationBannerText$: COLORS.Smart_ROS_All_Colors.Strong_Blue_900,
    sub_font$: COLORS.Smart_ROS_All_Colors.Gray_300,
    status_sub_font$: COLORS.Smart_ROS_All_Colors.Gray_100,
    keypad_font$: COLORS.Smart_ROS_All_Colors.Gray_30,
    disabled_button$: COLORS.Smart_ROS_All_Colors.Gray_500,
    disabled_icon$: COLORS.Smart_ROS_All_Colors.Gray_300,
    secondary_selected_button$: COLORS.Smart_ROS_All_Colors.Gray_700,
    secondary_selected_color$: COLORS.Smart_ROS_All_Colors.Tech_Blue_200,
    primary_selected_button$: COLORS.Smart_ROS_All_Colors.White,
    primary_selected_color$: COLORS.Smart_ROS_All_Colors.Tech_Blue_200,
    blue_font$: COLORS.Smart_ROS_All_Colors.Tech_Blue_200,
    main_green$: COLORS.Smart_ROS_All_Colors.Environmental_Green_700,
    sub_green$: COLORS.Smart_ROS_All_Colors.Environmental_Green_300,
    slider_circle_default$: COLORS.Smart_ROS_All_Colors.White,
    alarm_low$: COLORS.Smart_ROS_All_Colors.Safety_Orange_500,
    alarm_high$: COLORS.Smart_ROS_All_Colors.Warm_Red_700,
    grayish_one$: COLORS.Smart_ROS_All_Colors.Gray_400,
    grayish_two$: COLORS.Smart_ROS_All_Colors.Gray_500,
    grayish_three$: COLORS.Smart_ROS_All_Colors.Gray_600,
    graph_lines$: COLORS.Smart_ROS_All_Colors.Gray_500,
    gauge_base$: COLORS.Smart_ROS_All_Colors.Gray_500,
    red$: COLORS.Smart_ROS_All_Colors.Warm_Red_700,
    light_red$: COLORS.Smart_ROS_All_Colors.Warm_Red_300,
    very_light_red$: COLORS.Smart_ROS_All_Colors.Warm_Red_25,
    white$: COLORS.Smart_ROS_All_Colors.White,
    close_icon$: COLORS.Smart_ROS_All_Colors.Gray_700,
    menu_text_color$: COLORS.Smart_ROS_All_Colors.White,
    rosebud_circle0$: COLORS.Smart_ROS_All_Colors.Gray_700,
    rosebud_circle0_Fill$: COLORS.Smart_ROS_All_Colors.Gray_900,
    rosebud_circle1$: COLORS.Smart_ROS_All_Colors.Gray_600,
    rosebud_circle2$: COLORS.Smart_ROS_All_Colors.Gray_500,
    rosebud_circle3$: COLORS.Smart_ROS_All_Colors.Gray_400,
    rosebud_circle4$: COLORS.Smart_ROS_All_Colors.Gray_300,
    rosebud_circle5$: COLORS.Smart_ROS_All_Colors.Gray_200,
    rosebud_arrow1_color$: COLORS.Smart_ROS_All_Colors.Gray_200,
    rosebud_arrow2_color$: COLORS.Smart_ROS_All_Colors.Safety_Orange_700,
    rosebud_smalltext_color$: COLORS.Smart_ROS_All_Colors.Gray_300,
    rosebud_graduatedScale_textcolor$: COLORS.Smart_ROS_All_Colors.Gray_300,
    rosebud_text_color$: COLORS.Smart_ROS_All_Colors.Gray_100,
    rosebud_good_TF_5$: COLORS.Smart_ROS_All_Colors.Tech_Blue_200,
    rosebud_good_TF_4$: COLORS.Smart_ROS_All_Colors.Tech_Blue_300,
    rosebud_good_TF_3$: COLORS.Smart_ROS_All_Colors.Tech_Blue_500,
    rosebud_good_TF_2$: COLORS.Smart_ROS_All_Colors.Tech_Blue_700,
    rosebud_good_TF_1$: COLORS.Smart_ROS_All_Colors.Tech_Blue_900,
    rosebud_bad_TF_1$: COLORS.Smart_ROS_All_Colors.Warm_Red_900,
    rosebud_bad_TF_2$: COLORS.Smart_ROS_All_Colors.Warm_Red_700,
    rosebud_bad_TF_3$: COLORS.Smart_ROS_All_Colors.Warm_Red_500,
    rosebud_bad_TF_4$: COLORS.Smart_ROS_All_Colors.Warm_Red_300,
    rosebud_bad_TF_5$: COLORS.Smart_ROS_All_Colors.Warm_Red_100,
    toggleEffect$: COLORS.Smart_ROS_All_Colors.Strong_Blue_900,
}

export const Dark_Theme = new Theme("dark", Dark_Theme_Color_Map)